### PR TITLE
Less Ugly Readme Filetree

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
This adds emojis and makes the file tree easier to read! What's not to like?

### CODE REVIEW

**Comment by Hans5958** [comment]
I think it is better to leave it as it is because the structure is quite simple, and I think it is kinda ugly to have emojis inside of the code block.

**Comment by GrahamSH-LLK** [comment]
# manifest-schema

This repository hosts the schema for Scratch Addons' addon manifests.


    📦manifest-schema
     ┣ 📂1 # Folder with major version as the name
     ┃ ┗ 📜1.0.json # Schema with both major and minor version as the name
     ┣ 📜LICENSE
     ┗ 📜README.md

**Comment by GrahamSH-LLK** [comment]
I don't think that looks ugly...

**Comment by Hans5958** [comment]
Well, there could be some improvements to how the lines, if you know what I meant. How about this?
```bash
.
└── 📂 1 # Folder with major version as the name
    └── 📜 1.0.json # Schema with both major and minor version as the name
```
I still wanted to avoid emojis, but I think this is a better compromise. Other files should not be there as it is supposed to be simple and only explains the basic folder structure.

**Review by Hans5958 — APPROVED** [review]

**Pull request merged**
