### PR TITLE
Change property names for consistency changes on main repo

### PR DESCRIPTION
**Pull request by Hans5958**
Remind me to merge this when ScratchAddons/ScratchAddons#479 merges.

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Let me merge this first, then see if the other PR passes.

**Comment by WorldLanguages** [comment]
Oh nevermind, it still checks for the 1.1 schema. Let me try to fix that

**Comment by WorldLanguages** [comment]
Hmm I'm not 100% sure where the workflow is retrieved from - ScratchAddons' master? Your master? The origin branch from the PR? I merged the PR with its test failing because it was still on 1.1

**Comment by Hans5958** [comment]
Don't worry about the test. I have changed it 1.2 as per 04e4b11b470a4cb59887688c9bfb653c98e1c22e so future PRs and commits will follow 1.2 instead of 1.1.

**Pull request merged**
