### PR TITLE
Oh gosh this is too complex

### PR DESCRIPTION
**Pull request by apple502j**

### CODE REVIEW

**Comment by Hans5958** [comment]
Sorry for the delay. I was taking exams at that moment. Will check today.

I also see that ScratchAddons/ScratchAddons#2305 has been merged, so there will be no waiting after I done reviewing.

**Comment by TheColaber** [comment]
@Hans5958 Also be aware of https://github.com/ScratchAddons/ScratchAddons/pull/2326 and https://github.com/ScratchAddons/ScratchAddons/pull/2260 ... those will definitely be adding many tags

**Comment by Hans5958** [comment]
@TheColaber

Those are not related to this PR and should be made in another one.

**Review by Hans5958 — APPROVED** [review]
Going to merge this in a branch on this repo for conflict resolving and some changes. Will update after this branch is merged.

**Pull request merged**
